language: ruby
cache: yarn
env:
  - RAILS_ENV=test
before_install:
  # Checksum arbitrary fail: https://github.com/bundler/bundler/issues/5332
  - gem install -v 1.13.6 bundler --no-rdoc --no-ri
install:
  - bundle _1.13.6_ install --jobs=3 --retry=3
  - (yarn || npm install)
script:
  - bundle exec rails db:environment:set db:drop db:create db:migrate
  - bundle exec rspec
rvm:
  - 2.3.0
  - 2.3.1
