language: ruby
before_install:
  # Checksum arbitrary fail: https://github.com/bundler/bundler/issues/5332
  - gem install -v 1.13.6 bundler --no-rdoc --no-ri
  - bundle _1.13.6_ install
bundler_args: --without production
script:
  - bundle exec rails test
rvm:
  - 2.3.0
  - 2.3.1
